import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillFacebook,
  AiOutlineClose,
  AiOutlineMenu,
} from "react-icons/ai";
import { Link } from "react-scroll";
import Image from "next/image";
import oaksk from "../public/profile.jpg";
import Services from "./components/Services";
import Projects from "./components/Projects";
import Contact from "./components/Contact";
import Footer from "./components/Footer";
import { useState } from "react";
import About from "./components/About";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  let [open, setOpen] = useState(false);

  return (
    <div className={` ${darkMode ? "dark" : ""}`}>
      <Head>
        <title>Oak Soe Khant Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-50 md:px-10 transition-all duration-500 ease-in dark:bg-gray-900">
        {/* nav section starts */}
        <section id="nav" className="relative">
          <nav className="py-10 md:flex items-center justify-between dark:text-white">
            <h1 className="ml-6 mt-3 text-5xl font-burtons cursor-pointer">
              Oaksk
            </h1>
            <div
              onClick={() => setOpen(!open)}
              className="text-3xl absolute right-1 top-10 md:hidden cursor-pointer"
            >
              {open ? (
                <AiOutlineClose className="text-4xl mt-3 mr-5 dark:text-white stroke-2" />
              ) : (
                <AiOutlineMenu className="text-4xl mt-3 mr-5 dark:text-white stroke-2" />
              )}
            </div>
            <div
              className={`absolute min-h-fit w-screen bg-slate-50 dark:bg-gray-900 md:bg-none md:static md:min-h-fit md:w-auto items-center px-5 transition-all duration-500 ease-in ${
                open ? "right-0" : "right-[-200%] "
              }`}
            >
              <ul
                className={`flex md:flex-row flex-col font-medium md:items-center gap-6 py-2 text-center uppercase `}
              >
                <li className="text-lg pt-10 sm:pt-0 mb-3 transition-all cursor-pointer duration-300 hover:text-teal-600">
                  <Link activeClass="active" smooth spy to="home">
                    Home
                  </Link>
                </li>
                <li className="text-lg mb-3 transition-all cursor-pointer duration-300 hover:text-teal-600">
                  <Link
                    activeClass="active"
                    smooth
                    spy
                    offset={-100}
                    to="about"
                  >
                    About
                  </Link>
                </li>
                <li className="text-lg mb-3 transition-all cursor-pointer duration-300 hover:text-teal-600">
                  <Link
                    activeClass="active"
                    smooth
                    spy
                    offset={-100}
                    to="services"
                  >
                    Services
                  </Link>
                </li>
                <li className="text-lg mb-3 transition-all cursor-pointer duration-300 hover:text-teal-600">
                  <Link
                    activeClass="active"
                    smooth
                    spy
                    offset={-100}
                    to="projects"
                  >
                    Project
                  </Link>
                </li>
                <li className="text-lg mb-3 transition-all cursor-pointer duration-300 hover:text-teal-600">
                  <Link
                    activeClass="active"
                    smooth
                    spy
                    offset={100}
                    to="contact"
                  >
                    Contact
                  </Link>
                </li>
                <li
                  onClick={() => setDarkMode(!darkMode)}
                  className="md:ml-5 cursor-pointer"
                >
                  <BsFillMoonStarsFill className="inline cursor-pointer text-3xl hover:text-teal-600 duration-300 mb-10 md:mb-4" />
                </li>
                {/* {Links.map((URL) => (
                  <li key={URL.name} className="text-lg">
                    <a
                      href="URL.link"
                      className="transition-all duration-300 hover:text-teal-600"
                    >
                      {URL.name}
                    </a>
                  </li>
                ))} */}
              </ul>
            </div>
          </nav>
        </section>

        <section id="home">
          <div className="text-center p-10">
            <div className="mx-auto rounded-full overflow-hidden w-64 h-64 sm:h-96 sm:w-96">
              <Image src={oaksk} className="bg-cover" alt="Not Found" />
            </div>
            <h1 className="text-4xl my-6 md:my-10 py-2 text-teal-600 font-bold md:text-6xl">
              Oak Soe Khant
            </h1>
            <h3 className="text-xl py-2 md:text-3xl dark:text-white">
              Software Engineering Intern
            </h3>
            <p className="text-md py-5 leading-8 text-gray-500 md:text-xl dark:text-gray-400">
              4th year Student seeking for internship opportunities. Willing to
              exprerience real life problems and eager to learn the solutions.
            </p>
          </div>
          <div className="text-5xl mb-40 flex justify-center gap-16 py-3 dark:text-teal-600">
            <a href="https://www.facebook.com/oaksoekhant68/" target="blank">
              <AiFillFacebook className="hover:text-teal-400 transition-all duration-300 cursor-pointer " />
            </a>
            <a
              href="https://www.linkedin.com/in/oak-soe-khant-278475203/"
              target="blank"
            >
              <AiFillLinkedin className="hover:text-teal-400 transition-all duration-300 cursor-pointer text-grey-600" />
            </a>
            <a href="https://twitter.com/oaksk6820" target="blank">
              <AiFillTwitterCircle className="hover:text-teal-400 transition-all duration-300 cursor-pointer text-grey-600" />
            </a>
          </div>
        </section>

        <About />

        {/* design section starts */}
        <Services />

        {/* project section starts */}
        <Projects />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}
